Errata commit for commit 68f6eab10d557fe5549835a4acfece19c1ca739d
This commit is provided only to document a correction to a previous commit message.
Error: Missing .py extension in file name.
Correction:
Second commit.

File p10_1.py updated. Name of Eclipse project was wrong.